AWSTemplateFormatVersion: "2010-09-09"
Description: EnterOne Backend Vectorization Stack

###############################################################################
# PARAMETERS
###############################################################################
Parameters:
  EnvironmentName:
    Type: String
    Default: dev

  APIRepositoryName:
    Type: String
    Default: enterone/course-agent

  VectorizeFileRepositoryName:
    Type: String
    Default: enterone/vectorize

  EventHandlerRepositoryName:
    Type: String
    Default: enterone/event-handler

  ImageTag:
    Type: String
    Default: dev

  APIFunctionName:
    Type: String
    Default: enterone-website-course-agent-dev

  EventHandlerFunctionName:
    Type: String
    Default: enterone-website-event-handler-dev

  VectorizeFunctionName:
    Type: String
    Default: enterone-website-vectorize-file-dev

  ChatLogsBucketName:
    Type: String
    Default: course-agent-chatlogs-dev

  APIRoleName:
    Type: String
    Default: course-agent-role-dev

  EventHandlerRoleName:
    Type: String
    Default: event-handler-role-dev

  VectorizeRoleName:
    Type: String
    Default: vectorize-file-role-dev

  ApiGatewayName:
    Type: String
    Default: enterone-website-course-agent-api-dev

  MemorySize:
    Type: Number
    Default: 512

  TimeoutSeconds:
    Type: Number
    Default: 600

  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-091e93d060f4e78cf

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-090fe09a41e65518a, subnet-02c6b0991deaf9454

  ExistingTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0faf688d0c5337796

  PDFS3Bucket:
    Type: String
    Default: enterone-website-assets-staging

  AllowedOrigin:
    Type: String
    Default: https://d232n70twdz0lt.cloudfront.net

  ModelId:
    Type: String
    Default: global.anthropic.claude-haiku-4-5-20251001-v1:0


###############################################################################
# SECURITY GROUPS
###############################################################################
Resources:

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for Lambdas to connect to RDS & AOSS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  AllowLambdaIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref LambdaSecurityGroup
      GroupId: !Ref ExistingTargetSecurityGroup

  AllowLambdaEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      DestinationSecurityGroupId: !Ref ExistingTargetSecurityGroup
      GroupId: !Ref LambdaSecurityGroup


###############################################################################
# IAM ROLES
###############################################################################
  APILambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref APIRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EventHandlerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EventHandlerRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  VectorizeLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref VectorizeRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  VPCInterfacePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaVPCNetworkInterfaceAccess
      Roles:
        - !Ref APILambdaExecutionRole
        - !Ref EventHandlerRoleName
        - !Ref VectorizeLambdaExecutionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
              - ec2:AttachNetworkInterface
              - ec2:DetachNetworkInterface
            Resource: "*"

  AOSSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowAllAOSSOperations
      Roles:
        - !Ref VectorizeLambdaExecutionRole
        - !Ref APILambdaExecutionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: aoss:*
            Resource: "*"


###############################################################################
# SQS QUEUE
###############################################################################
  VectorizeDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${EnvironmentName}-vectorize-dlq"

  VectorizeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${EnvironmentName}-vectorize-queue"
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt VectorizeDLQ.Arn
        maxReceiveCount: 5


###############################################################################
# AOSS SECURITY POLICIES
###############################################################################
  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "encryption-${EnvironmentName}"
      Type: encryption
      Policy: !Sub |
        {
          "Rules":[{"ResourceType":"collection","Resource":["collection/${EnvironmentName}-collection"]}],
          "AWSOwnedKey":true
        }

  NetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "network-${EnvironmentName}"
      Type: network
      Policy: !Sub |
        [
          {
            "Rules":[
              {"ResourceType":"collection","Resource":["collection/${EnvironmentName}-collection"]},
              {"ResourceType": "dashboard", "Resource": ["collection/${EnvironmentName}-collection"]}
            ],
            "AllowFromPublic":true
          }
        ]

  OpenSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn: [EncryptionPolicy, NetworkPolicy]
    Properties:
      Name: !Sub "${EnvironmentName}-collection"
      Type: VECTORSEARCH

  DataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    DependsOn: [OpenSearchCollection]
    Properties:
      Name: !Sub "data-${EnvironmentName}"
      Type: data
      Policy: !Sub |
        [
          {
            "Rules":[
              {
                "ResourceType":"collection",
                "Resource":["collection/${EnvironmentName}-collection"],
                "Permission":[
                  "aoss:CreateCollectionItems",
                  "aoss:DeleteCollectionItems",
                  "aoss:UpdateCollectionItems",
                  "aoss:DescribeCollectionItems"
                ]
              },
              {
                "ResourceType":"index",
                "Resource":["index/${EnvironmentName}-collection/*"],
                "Permission":[
                  "aoss:CreateIndex","aoss:DeleteIndex","aoss:UpdateIndex",
                  "aoss:DescribeIndex","aoss:ReadDocument","aoss:WriteDocument"
                ]
              }
            ],
            "Principal":[
              "${APILambdaExecutionRole.Arn}",
              "${VectorizeLambdaExecutionRole.Arn}",
              "{{resolve:ssm:/enterone-course-agent-sso-roles-aoss/admin}}",
              "{{resolve:ssm:/enterone-course-agent-sso-roles-aoss/dev}}"
            ]
          }
        ]


###############################################################################
# S3 BUCKET
###############################################################################
  ChatLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ChatLogsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true


###############################################################################
# LAMBDAS
###############################################################################
  FastAPILambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref APIFunctionName
      Role: !GetAtt APILambdaExecutionRole.Arn
      Timeout: !Ref TimeoutSeconds
      MemorySize: !Ref MemorySize
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${APIRepositoryName}:${ImageTag}"
      Environment:
        Variables:
          BUCKET_NAME: !Ref ChatLogsBucket
          BUCKET_PREFIX: sessions/
          OPENSEARCH_HOST: !GetAtt OpenSearchCollection.CollectionEndpoint
          BEDROCK_ENDPOINT_URL: !Sub "https://bedrock-runtime.${AWS::Region}.amazonaws.com"
          REGION_NAME: !Ref AWS::Region
          MODEL_ID: !Ref ModelId
          USERNAME_DB: ai_agent_user
          PASSWORD_DB: D@taFlow!98zR
          HOST_DB: enterone-website-shared.cdc8m2awyyxs.us-east-2.rds.amazonaws.com
          DATABASE: website_staging
          INDEX_NAME: enterone-course-pdfs
          WIDGET_URL: !Ref AllowedOrigin
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref SubnetIds


  EventHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref EventHandlerFunctionName
      Role: !GetAtt EventHandlerLambdaExecutionRole.Arn
      Timeout: !Ref TimeoutSeconds
      MemorySize: !Ref MemorySize
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EventHandlerRepositoryName}:${ImageTag}"
      Environment:
        Variables:
          VECTORIZE_QUEUE_URL: !Ref VectorizeQueue
          USERNAME_DB: ai_agent_user
          PASSWORD_DB: D@taFlow!98zR
          HOST_DB: enterone-website-shared.cdc8m2awyyxs.us-east-2.rds.amazonaws.com
          DATABASE: website_staging
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref SubnetIds


  VectorizeFileLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref VectorizeFunctionName
      Role: !GetAtt VectorizeLambdaExecutionRole.Arn
      Timeout: !Ref TimeoutSeconds
      MemorySize: !Ref MemorySize
      ReservedConcurrentExecutions: 10
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${VectorizeFileRepositoryName}:${ImageTag}"
      Environment:
        Variables:
          OPENSEARCH_HOST: !GetAtt OpenSearchCollection.CollectionEndpoint
          BEDROCK_ENDPOINT_URL: !Sub "https://bedrock-runtime.${AWS::Region}.amazonaws.com"
          REGION_NAME: !Ref AWS::Region
          MODEL_ID: us.anthropic.claude-sonnet-4-5-20250929-v1:0
          INDEX_NAME: enterone-course-pdfs
          S3_BUCKET: !Ref PDFS3Bucket
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref SubnetIds


###############################################################################
# SQS → VECTORIZE LAMBDA EVENT SOURCE
###############################################################################
  VectorizeLambdaSQSESM:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt VectorizeQueue.Arn
      FunctionName: !Ref VectorizeFileLambda
      BatchSize: 1
      MaximumBatchingWindowInSeconds: 5
      Enabled: true
      ScalingConfig:
        MaximumConcurrency: 10

###############################################################################
# API GATEWAY + CORS
###############################################################################
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiGatewayName
      EndpointConfiguration:
        Types: ["REGIONAL"]

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: api
      RestApiId: !Ref RestApi

  ApiV1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: v1
      RestApiId: !Ref RestApi

  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiV1Resource
      PathPart: "{proxy+}"
      RestApiId: !Ref RestApi

  ApiV1AnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiV1Resource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPILambda.Arn}/invocations

  ProxyAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPILambda.Arn}/invocations
        TimeoutInMillis: 90000

  # CORS OPTIONS
  ProxyOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProxyResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: !Sub "'${AllowedOrigin}'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"

            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true
          # ResponseModels:
          #  application/json: "Empty"


  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FastAPILambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiV1AnyMethod
      - ProxyAnyMethod
      - ProxyOptionsMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: !Ref EnvironmentName

###############################################################################
# OUTPUTS
###############################################################################
Outputs:
  ApiInvokeUrl:
    Description: Base Invoke URL for the API
    Value: !Sub https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/api/v1/
