AWSTemplateFormatVersion: "2010-09-09"
Description: Placeholder

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  APIRepositoryName:
    Type: String
    Default: enterone/course-agent
  VectorizeFileRepositoryName:
    Type: String
    Default: enterone/vectorize
  EventHandlerRepositoryName:
    Type: String
    Default: enterone/event-handler
  ImageTag:
    Type: String
    Default: latest
  APIFunctionName:
    Type: String
    Default: enterone-website-dev-course-agent
  EventHandlerFunctionName:
    Type: String
    Default: enterone-website-dev-event-handler
  VectorizeFunctionName:
    Type: String
    Default: enterone-website-dev-vectorize-file
  ChatLogsBucketName:
    Type: String
    Default: course-agent-chatlogs
  APIRoleName:
    Type: String
    Default: course-agent-role
  EventHandlerRoleName:
    Type: String
    Default: event-handler-role
  VectorizeRoleName:
    Type: String
    Default: vectorize-file-role
  ApiGatewayName:
    Type: String
    Default: enterone-website-course-agent-api-dev
  MemorySize:
    Type: Number
    Default: 512
  TimeoutSeconds:
    Type: Number
    Default: 600
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-091e93d060f4e78cf
  SubnetIds:
    Description: List
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-090fe09a41e65518a, subnet-02c6b0991deaf9454
  ExistingTargetSecurityGroup:
    Description: Security group for the existing RDS database
    Type: AWS::EC2::SecurityGroup::Id
  PDFS3Bucket:
    Description: S3 Bucket where course PDFs are stored
    Type: String
    Default: enterone-website-assets-staging

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for Lambda to connect to RDS/service
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  AllowLambdaIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref LambdaSecurityGroup
      GroupId: !Ref ExistingTargetSecurityGroup

  AllowLambdaEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      DestinationSecurityGroupId: !Ref ExistingTargetSecurityGroup
      GroupId: !Ref LambdaSecurityGroup

  APILambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref APIRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EventHandlerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EventHandlerRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess

  VectorizeLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref VectorizeRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  VPCInterfacePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaVPCNetworkInterfaceAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
              - ec2:AttachNetworkInterface
              - ec2:DetachNetworkInterface
            Resource: "*"
      Roles:
        - !Ref APILambdaExecutionRole
        - !Ref EventHandlerRoleName
        - !Ref VectorizeLambdaExecutionRole

  AOSSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowAllAOSSOperations
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - aoss:*
            Resource: "*"
      Roles:
        - !Ref VectorizeLambdaExecutionRole
        - !Ref APILambdaExecutionRole

  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: "encryption"
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/collection"]
            }
          ],
          "AWSOwnedKey": true
        }

  NetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: "network"
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/collection"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  OpenSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn:
      - EncryptionPolicy
      - NetworkPolicy
    Properties:
      Name: "collection"
      Type: VECTORSEARCH

  DataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    DependsOn:
      - OpenSearchCollection
    Properties:
      Name: "data"
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/collection"],
                "Permission": [
                  "aoss:CreateCollectionItems",
                  "aoss:DeleteCollectionItems",
                  "aoss:UpdateCollectionItems",
                  "aoss:DescribeCollectionItems"
                ]
              },
              {
                "ResourceType": "index",
                "Resource": ["index/collection/*"],
                "Permission": [
                  "aoss:CreateIndex",
                  "aoss:DeleteIndex",
                  "aoss:UpdateIndex",
                  "aoss:DescribeIndex",
                  "aoss:ReadDocument",
                  "aoss:WriteDocument"
                ]
              }
            ],
            "Principal": [
              "${APILambdaExecutionRole.Arn}",
              "${VectorizeLambdaExecutionRole.Arn}"
            ]
          }
        ]

  ChatLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ChatLogsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FastAPILambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref APIFunctionName
      Role: !GetAtt APILambdaExecutionRole.Arn
      Timeout: !Ref TimeoutSeconds
      MemorySize: !Ref MemorySize
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${APIRepositoryName}:${ImageTag}"
      Environment:
        Variables:
          BUCKET_NAME: !Ref ChatLogsBucket
          BUCKET_PREFIX: sessions/
          OPENSEARCH_HOST: !GetAtt OpenSearchCollection.CollectionEndpoint
          BEDROCK_ENDPOINT_URL: !Sub "https://bedrock-runtime.${AWS::Region}.amazonaws.com"
          REGION_NAME: !Ref AWS::Region
          MODEL_ID: us.anthropic.claude-sonnet-4-5-20250929-v1:0
          USERNAME_DB: ai_agent_user
          PASSWORD_DB: D@taFlow!98zR
          HOST_DB: enterone-website-shared.cdc8m2awyyxs.us-east-2.rds.amazonaws.com
          DATABASE: website_staging
          INDEX_NAME: enterone-course-pdfs
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds: !Ref SubnetIds

  EventHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref EventHandlerFunctionName
      Role: !GetAtt EventHandlerLambdaExecutionRole.Arn
      Timeout: !Ref TimeoutSeconds
      MemorySize: !Ref MemorySize
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EventHandlerRepositoryName}:${ImageTag}"
      Environment:
        Variables:
          STEP_FUNCTION_ARN: !Ref VectorizeFileStateMachine
          USERNAME_DB: ai_agent_user
          PASSWORD_DB: D@taFlow!98zR
          HOST_DB: enterone-website-shared.cdc8m2awyyxs.us-east-2.rds.amazonaws.com
          DATABASE: website_staging
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds: !Ref SubnetIds

  VectorizeFileLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref VectorizeFunctionName
      Role: !GetAtt VectorizeLambdaExecutionRole.Arn
      Timeout: !Ref TimeoutSeconds
      MemorySize: !Ref MemorySize
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${VectorizeFileRepositoryName}:${ImageTag}"
      Environment:
        Variables:
          OPENSEARCH_HOST: !GetAtt OpenSearchCollection.CollectionEndpoint
          BEDROCK_ENDPOINT_URL: !Sub "https://bedrock-runtime.${AWS::Region}.amazonaws.com"
          REGION_NAME: !Ref AWS::Region
          MODEL_ID: us.anthropic.claude-sonnet-4-5-20250929-v1:0
          INDEX_NAME: enterone-course-pdfs
          S3_BUCKET: !Ref PDFS3Bucket
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds: !Ref SubnetIds

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt VectorizeFileLambda.Arn

  VectorizeFileStateMachine:
    Type: AWS::StepFunctions::StateMachine
    DependsOn:
      - StepFunctionRole
      - VectorizeFileLambda
    Properties:
      RoleArn: !GetAtt StepFunctionRole.Arn
      StateMachineName: !Sub "${AWS::StackName}-vectorize-file-${EnvironmentName}"
      StateMachineType: STANDARD
      DefinitionString: !Sub |
        {
          "Comment": "Step Functions to Vectorize a File and upload to AOSS collection",
          "StartAt": "VectorizeFile",
          "States": {
            "VectorizeFile": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "OutputPath": "$.Payload",
              "Parameters": {
                "Payload.$": "$",
                "FunctionName": "${VectorizeFileLambda.Arn}"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 1,
                  "MaxAttempts": 3,
                  "BackoffRate": 2,
                  "JitterStrategy": "FULL"
                }
              ],
              "End": true
            }
          }
        }

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiGatewayName
      EndpointConfiguration:
        Types: ["REGIONAL"]

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: api
      RestApiId: !Ref RestApi

  ApiV1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: v1
      RestApiId: !Ref RestApi

  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiV1Resource
      PathPart: "{proxy+}"
      RestApiId: !Ref RestApi

  ApiV1AnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiV1Resource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPILambda.Arn}/invocations

  ProxyAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPILambda.Arn}/invocations

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FastAPILambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*/*

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiV1AnyMethod
      - ProxyAnyMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: !Ref EnvironmentName

  # InvokeOnCreate:
  #   Type: AWS::CloudFormation::CustomResource
  #   DependsOn:
  #     - EventHandlerLambda
  #   Properties:
  #     ServiceToken: !GetAtt EventHandlerLambda.Arn
  #     ServiceTimeout: 600

Outputs:
  ApiInvokeUrl:
    Description: Base Invoke URL for the API
    Value: !Sub https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/api/v1/
